// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PageParamsProvider as PageParamsProvider__ } from "@plasmicapp/react-web/lib/host";
import { PlasmicFormUi } from "../components/plasmic/website_starter/PlasmicFormUi";
import { useRouter } from "next/router";
import OfferPDFDownloader from "../components/OfferPDFDownloader";

function FormUi() {
  return (
    <PageParamsProvider__
      route={useRouter()?.pathname}
      params={useRouter()?.query}
      query={useRouter()?.query}
    >
      <div>
        <PlasmicFormUi />
        
      </div>
    </PageParamsProvider__>
  );
}

export default FormUi;