/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: sDZjsPZfHxS5aFWp43RghU

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariants_6M7Ny4P2F7 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 6m7NY-4P2f-7/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariants_6M7Ny4P2F7
});
